export { default as Entity } from './Entity/Entity.jsx'
export { default as Mazepvz2 } from './Mazepvz2/Mazepvz2.jsx'
export { default as Mazefernan } from './Mazefernan/Mazefernan.jsx'
export { default as Tiempo} from './Tiempo/Tiempo.jsx'
export { default as Laberinto} from './Laberinto/Laberinto.jsx'
export { default as Inputs } from './Inputs/Inputs.jsx'
export { default as Buttons } from './Buttons/Buttons.jsx'
